# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=255, verbose_name='Recipient id')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code')),
                ('origin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origin')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination')),
                ('at', models.DateField(blank=True, null=True, verbose_name='At')),
                ('notify_emails', models.TextField(blank=True, null=True, verbose_name='Notify emails')),
                ('status', models.CharField(choices=[('I', 'Init')], default='I', max_length=1, verbose_name='Status')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ('-updated_at',),
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
