# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.TextField(blank=True, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.TextField(blank=True, null=True, verbose_name='Origin'),
        ),
    ]
