# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170815_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient name'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('I', 'Init'), ('W', 'Waiting'), ('C', 'Canceled'), ('A', 'Arrived'), ('H', 'Help'), ('O', 'OK')], default='I', max_length=1, verbose_name='Status'),
        ),
    ]
